### ISSUE TITLE
Upgrade liquibase to 3.2.2

### ISSUE THREAD

**Issue by tinhtruong** [tlberglund/gradle-liquibase-plugin#21]
Hi,

Liquibase 3.2.2 is out, I am not sure if we can upgrade to that version?

Tinh

**Comment by ianbrandt** [comment]
@stevesaliman Thanks for the info, and apologies for my very late reply.

Correct me if I'm wrong, but it sounds like all the issues you mention have to do with the integration of Liquibase and the Groovy DSL.  I'm using almost exclusively `<sql>` and `<sqlFile>` changes in my Liquibase change logs, so the Groovy DSL is of less interest for my purposes.  I'd prefer to use a Gradle Liquibase Plugin with XML change logs if that meant it would stay in step with Liquibase releases.

Would it be possible to split this plugin in two?  The gradle-liquibase-plugin would simply wrap the execution of out-of-the-box Liquibase functionality, and hence could more easily keep up with Liquibase versions.  A gradle-liquibase-dsl-plugin (or what have you) could add the Groovy DSL features on top of that.  If the latter faced greater challenges updating to new Liquibase versions it could lag behind without impacting those not using the DSL.

**Comment by stevesaliman** [comment]
I'm working from memory here - which is always a dangerous thing but...

The Gradle plugin simply registers the Groovy DSL as a valid parser for groovy files, then calls the core Liquibase code using whatever changeset you've defined.  You should be able to use XML files by simply defining an XML file in the ```changelogs``` block.

Long term, I'd like to make the version of Liquibase that the plugin uses a configuration item, similar to what I'm doing in the Gradle cobertura plugin, but until then, I think you can override the dependencies I'm using and bring in whatever version of Liquibase you need using Gradles normal exclusion mechanisms - especially if you're using XML based changelogs.

I'll test this over the weekend since I need to look at a pull request that might work for Liquibase 3.3.

**Comment by stevesaliman** [comment]
I ran a quick test, and my memory appears to be working for once :-)

If you specify a change log file that ends in .xml, the Gradle plugin will use the XML parser that is build into Liquibase instead of the Groovy DSL.

I've uploaded a 1.0.1-SNAPSHOT of both the plugin and the Groovy DSL to the Sontatype snapshot repo, and they now fully support Liquibase 3.3.2.

If you ever need a different version of Liquibase itself, you can exclude the org.liquibase:liquibase-core dependency from the plugin, and include whatever version you need - as long as it is 3.2 or later.

Give them a try and let me know how they are working for you.  I hope to have production releases by the weekend.

**Comment by stevesaliman** [comment]
Version 1.0.1 of the plugin now supports Liquibae 3.3.2, and I've cleaned up the documentation to talk about using the plugin with XML changelogs, though I'm not sure why anyone would want to use XML over the Groovy DSL :-)
